### ISSUE TITLE
.envファイルの管理

### ISSUE THREAD

**Issue by sunakane** [ynct-d-members/todo-team#27]
.envファイルはDBのパスワードのほか，環境依存の値が入るファイルになっていくと思われるので，

1. .env.templateをgitで管理
2. ローカルで.envにコピーして必要な部分を変更

の流れにしたい

**Comment by shippokun** [comment]
ならdotenvが必要？

**Comment by sunakane** [comment]
dotenvはここでは必要ではないと思う．
単純に現在のmainブランチにある.envに認証情報ガッチリ書いてあるのが嫌だったので

**Comment by sunakane** [comment]
dotenvパッケージ導入はたぶんデプロイするときとかに必要になってくるんでそんとき考えることにしましょ
